trigger:
  branches:
    include:
      - develop
      - main
  paths:
    include:
      - backend/**
      - frontend/**
      - azure-pipelines.yml
      - .azure-pipelines/**

pr:
  branches:
    include:
      - develop
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: frontend-secrets
  - group: development-variables
  - group: production-variables

stages:
  - stage: CI
    displayName: Build & Test
    jobs:
      - job: backend
        displayName: Backend CI
        steps:
          - template: .azure-pipelines/templates/backend-ci.yml
            parameters:
              buildConfiguration: $(BUILD_CONFIGURATION)
              nugetCache: $(Pipeline.Workspace)/.nuget/packages
              projects: $(BACKEND_PROJECTS)
              testProjects: $(BACKEND_TEST_PROJECTS)

      - job: frontend
        displayName: Frontend CI
        steps:
          - template: .azure-pipelines/templates/frontend-ci.yml
            parameters:
              frontendPath: $(FRONTEND_PATH)
              nodeVersion: $(NODE_VERSION)

  - template: .azure-pipelines/templates/deploy-stage.yml
    parameters:
      azureSubscription: sportson-connection
      backendAppName: $(BACKEND_APP_NAME)
      backendArtifactName: backend
      backendAppType: $(BACKEND_APP_TYPE)
      branch: develop
      environment: $(AZDO_ENVIRONMENT_NAME)
      frontendAppName: $(FRONTEND_APP_NAME)
      frontendArtifactName: frontend
      frontendToken: $(SWA_DEPLOYMENT_TOKEN)
      stageName: Deploy_Dev

  - template: .azure-pipelines/templates/deploy-stage.yml
    parameters:
      azureSubscription: sportson-connection
      backendAppName: $(BACKEND_APP_NAME_PROD)
      backendAppSettings: '-CONNECTION_STRING_PROD "$(CONNECTION_STRING_PROD)"'
      backendArtifactName: backend
      backendAppType: $(BACKEND_APP_TYPE)
      branch: main
      environment: $(AZDO_ENVIRONMENT_NAME_PROD)
      frontendAppName: $(FRONTEND_APP_NAME_PROD)
      frontendArtifactName: frontend
      frontendToken: $(SWA_DEPLOYMENT_TOKEN_PROD)
      stageName: Deploy_Prod
