parameters:
  appLocation: frontend
  outputLocation: dist

steps:
  - task: AzureStaticWebApp@0
    displayName: Deploy frontend
    inputs:
      app_location: ${{ parameters.appLocation }}
      output_location: ${{ parameters.outputLocation }}
      azure_static_web_apps_api_token: $(SWA_DEPLOYMENT_TOKEN)